name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: remove the file if already exist
      run: sudo rm -rf nodejs-test/
    - name: cloning the github repo
      run: git clone https://github.com/signiance-assignment/nodejs-test.git
    - name: running npm command
      run: npm install
    - name: installing pm2 package
      run: sudo npm install -g pm2
    - name: running nodejsapp
      run: pm2 start /home/ubuntu/actions-runner/_work/nodejsrepo/nodejsrepo/nodejs-test/index.js --name=nodejs-test
