name: CD Pipeline

#on:
 # workflow_run:
  #  workflows: ["Node.js CI"]
   # types:
      - completed

jobs:

  build:

    runs-on: self-hosted
    steps:
    - name: remove the file if already exist
      run: sudo rm -rf nodejs-test/
    - name: cloning the github repo
      run: git clone https://github.com/signiance-assignment/nodejs-test.git
    - name: switching to that directory
      run: cd nodejs-test
    - name: running npm command
      run: npm install
