name: CD Pipeline

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: running npm command
      run: npm install
    - name: running nodejsapp
      run: node index.js
