name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm install
      
   deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master   #3rd party github action
        with:
          host: ${{secrets.HOST }}
          username: ${{secrets.USER }}
          key: ${{secrets.KEY }}
          port: ${{secrets.PORT }}

          script:
            npm install
            npm run build
            node index.js
