name: nodejsrepo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: get the code
      - uses: actions/checkout@v3
      - name: Use node js
        uses: actions/steup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run:
          npm install
          npm run build

        env:
          CI: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master   #3rd party github action
        with:
          host: ${{secrets.HOST }}
          username: ${{secrets.USER }}
          key: ${{secrets.KEY }}
          port: ${{secrets.PORT }}

          script:
            npm install
            npm run build
            node index.js
            
